
# Improve bvlc/caffe:cpu
# What will this dockerfile do
# 1. update system
# 2. install vim
# Until here. tag is V1.0

FROM bvlc/caffe:cpu
MAINTAINER advsail

RUN apt-get update
RUN apt-get install -y vim


